services:
  mongo:
    image: mirror.gcr.io/library/mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27020:27017"
    networks: [mongo-network]

  calculator:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://admin_user:web3@mongo:27017/?authSource=admin
    depends_on:
      - mongo
    ports:
      - "8089:8000"
    networks: [mongo-network]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - calculator
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
