name: Backend - Build & Push

on:
  push:
    branches:
      - main
      - 'release/*'
    tags:
      - 'v*'
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          cd backend
          pytest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: vars
        run: |
          # Usa GITHUB_REF para detectar si el push fue un tag
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "TAG=$TAG" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Determine image name (lowercase)
        run: |
          # Convierte el nombre del repositorio a minúsculas y añade el sufijo /backend
          IMAGE=ghcr.io/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/calculator-backend
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          echo "Building image: $IMAGE:$TAG"
          docker build -t $IMAGE:$TAG ./backend

      - name: Push Docker image
        run: |
          echo "Pushing image: $IMAGE:$TAG"
          docker push $IMAGE:$TAG
