name: Build and Push Backend Docker Image
on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "backend/**"
      - ".github/workflows/backend-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image vars (lowercase) and tag
        id: vars
        shell: bash
        run: |
          # ↓↓↓ Convierte TODO owner/repo a minúsculas de una sola vez
          REPO_FULL_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          OWNER_LC="${REPO_FULL_LC%%/*}"
          REPO_LC="${REPO_FULL_LC#*/}"

          # Imagen separada para backend
          echo "IMAGE=ghcr.io/${OWNER_LC}/${REPO_LC}-backend" >> $GITHUB_ENV

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Show image (debug)
        run: |
          echo "IMAGE=${{ env.IMAGE }}"
          echo "TAG=${{ env.TAG }}"

      - name: Build Docker image
        run: |
          docker build -t "${{ env.IMAGE }}:${{ env.TAG }}" ./backend

      - name: Push Docker image
        run: |
          docker push "${{ env.IMAGE }}:${{ env.TAG }}"
