name: Build and Push Frontend Docker Image
on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-build.yml"

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Necesario para subir a GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image vars (lowercase) and tag
        id: vars
        shell: bash
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_ONLY="${GITHUB_REPOSITORY#*/}"
          REPO_LC=$(echo "${REPO_ONLY}" | tr '[:upper:]' '[:lower:]')

          # Imagen separada para frontend
          echo "IMAGE=ghcr.io/${OWNER_LC}/${REPO_LC}-frontend" >> $GITHUB_ENV

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV   # ej: v1.2.3
          else
            echo "TAG=latest" >> $GITHUB_ENV               # push a main
          fi

      - name: Build Docker image
        shell: bash
        run: |
          docker build -t "${{ env.IMAGE }}:${{ env.TAG }}" ./frontend

      - name: Push Docker image
        run: |
          docker push "${{ env.IMAGE }}:${{ env.TAG }}"
